// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj4-IT0eeslWzmrV7UTjHx_TxtCiPE8KE',
    appId: '1:629178175007:web:d92e0f699fb6ce92ea0f2a',
    messagingSenderId: '629178175007',
    projectId: 'lms-anshuman',
    authDomain: 'lms-anshuman.firebaseapp.com',
    databaseURL: 'https://lms-anshuman-default-rtdb.firebaseio.com',
    storageBucket: 'lms-anshuman.firebasestorage.app',
    measurementId: 'G-X54VVC5HTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ-AGLIkwR8iVeKmPf1Qw--qTwTot4lwY',
    appId: '1:629178175007:android:d1abc777c74419ffea0f2a',
    messagingSenderId: '629178175007',
    projectId: 'lms-anshuman',
    databaseURL: 'https://lms-anshuman-default-rtdb.firebaseio.com',
    storageBucket: 'lms-anshuman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvneIJvcGvQb7JweqVheYKcllJ_RSU-a8',
    appId: '1:629178175007:ios:5a8bd9c407ae4e0dea0f2a',
    messagingSenderId: '629178175007',
    projectId: 'lms-anshuman',
    databaseURL: 'https://lms-anshuman-default-rtdb.firebaseio.com',
    storageBucket: 'lms-anshuman.firebasestorage.app',
    iosBundleId: 'com.example.stelaApp',
  );
}
