import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:stela_app/splash.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:stela_app/theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Minimal launch delay for native splash screen sync
  await Future.delayed(const Duration(milliseconds: 300));

  // Initialize Firebase using the fresh client config file generated by CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Web-specific settings
  if (kIsWeb) {
    FirebaseFirestore.instance.settings = const Settings(
      persistenceEnabled: true,
    );

    final opts = Firebase.app().options;
    print('Firebase(web) initialized for projectId=${opts.projectId}');
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'STELA',
      theme: AppTheme.light,
      home: const Splash(),
      debugShowCheckedModeBanner: false,
    );
  }
}
